export const userRows = [
  {
    id: 1,
    nombre_completo: "Administrador",
    correo_electronico: "administrador@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Administrador",
    estado: "Activo",
  },
  {
    id: 2,
    nombre_completo: "Pepito Fdez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Dinamizador",
    estado: "Activo",
  },
  {
    id: 3,
    nombre_completo: "Juan Carlos",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Auxiliar",
    estado: "Deshabilitado",
  },
  {
    id: 4,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  {
    id: 5,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  {
    id: 6,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  {
    id: 7,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  {
    id: 8,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  {
    id: 9,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  {
    id: 10,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  {
    id: 12,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  {
    id: 13,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
];

export const maquinaryRows = [
  {
    id: 1,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 2,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 3,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 4,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 5,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 6,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 7,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 8,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 9,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 10,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 12,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
  {
    id: 13,
    descripcion_equipo:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal: "Proyecto CTeI",
  },
];

export const talentRows = [
  {
    id: 1,
    nombre_persona: "Pepe Fedz",
    nivel_academico: "pepr@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Vigente",
  },
  {
    id: 2,
    nombre_persona: "Pepito Fdez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Auxiliar",
    estado_contrato: "Concluido",
  },
  {
    id: 3,
    nombre_persona: "Juan Carlos",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Planta",
    estado_contrato: "Vigente",
  },
  {
    id: 4,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Concluido",
  },
  {
    id: 5,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Concluido",
  },
  {
    id: 6,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Auxiliar",
    estado_contrato: "Vigente",
  },
  {
    id: 7,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Vigente",
  },
  {
    id: 8,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Concluido",
  },
  {
    id: 9,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Concluido",
  },
  {
    id: 10,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Concluido",
  },
  {
    id: 12,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Concluido",
  },
  {
    id: 13,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Concluido",
  },
];

export const productRows = [
  {
    id: 65879,
    nombre_producto: "Producto alto",
    tipologia_producto: "Productos Tecnologicos",
    fecha_registro: "22/02/2020",
    semillero: "Desarrollo",
    talento_humano: "Pepe Fdez, Carlos, Alexis",
  },
  {
    id: 65177,
    nombre_producto: "Producto alto",
    tipologia_producto: "Productos Tecnologicos",
    fecha_registro: "15/02/2020",
    semillero: "Investigacion",
    talento_humano: "Carlos, Alexis",
  },
  {
    id: 65168,
    nombre_producto: "Producto alto",
    tipologia_producto: "Productos Emprendimiento",
    fecha_registro: "02/02/2020",
    semillero: "Investigacion",
    talento_humano: "Pepe Fdez",
  },
  {
    id: 65158,
    nombre_producto: "Producto alto",
    tipologia_producto: "Notas Cientificas",
    fecha_registro: "15/08/2020",
    semillero: "Diseño",
    talento_humano: "Susan",
  },
  {
    id: 65068,
    nombre_producto: "Producto alto",
    tipologia_producto: "Productos Emprendimiento",
    fecha_registro: "02/02/2020",
    semillero: "Investigacion",
    talento_humano: "Pepe Fdez",
  },
  {
    id: 65468,
    nombre_producto: "Producto alto",
    tipologia_producto: "Productos Emprendimiento",
    fecha_registro: "02/02/2020",
    semillero: "Investigacion",
    talento_humano: "Pepe Fdez",
  },
  {
    id: 64168,
    nombre_producto: "Producto alto",
    tipologia_producto: "Productos Emprendimiento",
    fecha_registro: "02/02/2020",
    semillero: "Investigacion",
    talento_humano: "Pepe Fdez",
  },
  {
    id: 63168,
    nombre_producto: "Producto alto",
    tipologia_producto: "Productos Emprendimiento",
    fecha_registro: "02/02/2020",
    semillero: "Investigacion",
    talento_humano: "Pepe Fdez",
  },
  {
    id: 62168,
    nombre_producto: "Producto alto",
    tipologia_producto: "Productos Emprendimiento",
    fecha_registro: "02/02/2020",
    semillero: "Investigacion",
    talento_humano: "Pepe Fdez",
  }
];

export const finanzaData = [
  {
    name: "2017",
    "Inversion": 4000,
  },
  {
    name: "2018",
    "Inversion": 2113,
  },
  {
    name: "2019",
    "Inversion": 3653,
  },
  {
    name: "2020",
    "Inversion": 5832,
  },
  {
    name: "2021",
    "Inversion": 2454,
  },
];