export const userRows = [
  {
    id: 1,
    nombre_completo: "Administrador",
    correo_electronico: "administrador@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Administrador",
    estado: "Activo",
  },
  {
    id: 2,
    nombre_completo: "Juan Fernando Alzate",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de los Recursos Naturales Renovables -La Salada",
    rol: "Dinamizador",
    estado: "Activo",
  },
  {
    id: 3,
    nombre_completo: "Juan Carlos Sanchez",
    correo_electronico: "Carlos@gmail.com",
    centro_formacion: "Centro de Tecnología de la Manufactura Avanzada",
    rol: "Auxiliar",
    estado: "Deshabilitado",
  },
  {
    id: 4,
    nombre_completo: "Santiago Ventrez",
    correo_electronico: "fdez@gmail.com",
    centro_formacion: "Centro de Servicios y Gestion Empresarial",
    rol: "Aprendiz",
    estado: "Suspendido",
  },
  // {
  //   id: 5,
  //   nombre_completo: "Santiago Ventrez",
  //   correo_electronico: "fdez@gmail.com",
  //   centro_formacion: "Centro de Servicios y Gestion Empresarial",
  //   rol: "Aprendiz",
  //   estado: "Suspendido",
  // },
  // {
  //   id: 6,
  //   nombre_completo: "Santiago Ventrez",
  //   correo_electronico: "fdez@gmail.com",
  //   centro_formacion: "Centro de Servicios y Gestion Empresarial",
  //   rol: "Aprendiz",
  //   estado: "Suspendido",
  // },
  // {
  //   id: 7,
  //   nombre_completo: "Santiago Ventrez",
  //   correo_electronico: "fdez@gmail.com",
  //   centro_formacion: "Centro de Servicios y Gestion Empresarial",
  //   rol: "Aprendiz",
  //   estado: "Suspendido",
  // },
  // {
  //   id: 8,
  //   nombre_completo: "Santiago Ventrez",
  //   correo_electronico: "fdez@gmail.com",
  //   centro_formacion: "Centro de Servicios y Gestion Empresarial",
  //   rol: "Aprendiz",
  //   estado: "Suspendido",
  // },
  // {
  //   id: 9,
  //   nombre_completo: "Santiago Ventrez",
  //   correo_electronico: "fdez@gmail.com",
  //   centro_formacion: "Centro de Servicios y Gestion Empresarial",
  //   rol: "Aprendiz",
  //   estado: "Suspendido",
  // },
  // {
  //   id: 10,
  //   nombre_completo: "Santiago Ventrez",
  //   correo_electronico: "fdez@gmail.com",
  //   centro_formacion: "Centro de Servicios y Gestion Empresarial",
  //   rol: "Aprendiz",
  //   estado: "Suspendido",
  // },
  // {
  //   id: 12,
  //   nombre_completo: "Santiago Ventrez",
  //   correo_electronico: "fdez@gmail.com",
  //   centro_formacion: "Centro de Servicios y Gestion Empresarial",
  //   rol: "Aprendiz",
  //   estado: "Suspendido",
  // },
  // {
  //   id: 13,
  //   nombre_completo: "Santiago Ventrez",
  //   correo_electronico: "fdez@gmail.com",
  //   centro_formacion: "Centro de Servicios y Gestion Empresarial",
  //   rol: "Aprendiz",
  //   estado: "Suspendido",
  // },
];

export const maquinaryRows = [
  {
    id: 1,
    descripcion_equipo:
      "ASUS VivoBook 14 agrega estilo y dinamismo a la informática diaria. Con su procesador AMD Ryzen 3  y SSD PCIe ® de gran capacidad para un almacenamiento súper rápido., VivoBook 14 proporciona la potencia que necesita para hacer las cosas",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2020",
    tipo_de_equipo: "Portatil",
    proyecto_principal:
      "Blockchain como solución tecnológica para la gestión de firmas digitales utilizando sistemas de reconocimiento biométrico",
  },
  {
    id: 2,
    descripcion_equipo:
      "Telescopio con Lentes ópticas de vidrio HD, con adaptador de teléfono, obturador de cable de cámara, filtro de luna, bolsa de transporte y te obsequiamos Monocular de 12x50 PARA OBSERVACION ASTRONOMICA Y TERRESTRE.",
    valor_equipo: "$15.458.164",
    fecha_compra: "01/02/2020",
    tipo_de_equipo: "Telescopios",
    proyecto_principal:
      "Estrategias didácticas mediante herramientas Lego para el desarrollo de habilidades blandas de los aprendices del  Centro de Servicios y Gestión Empresarial.",
  },
  {
    id: 3,
    descripcion_equipo:
      "El sensor de imagen de la D3500 es, aproximadamente, 15 veces más grande que aquellos que se usan en los teléfonos inteligentes de gama básica. Esto quiere decir que obtendrá fotos más claras, nítidas y con mayor detalle; fotos que captarán la atención de inmediato y recibirán muchos Me gusta",
    valor_equipo: "$15.458.164",
    fecha_compra: "22/05/2019",
    tipo_de_equipo: "Camaras",
    proyecto_principal:
      "Implementación de un laboratorio para formulación de proyectos, anílisis y procesamiento de datos fortaleciendo la investigación del Centro de Servicios y Gestión Empresarial",
  },
  // {
  //   id: 4,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
  // {
  //   id: 5,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
  // {
  //   id: 6,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
  // {
  //   id: 7,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
  // {
  //   id: 8,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
  // {
  //   id: 9,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
  // {
  //   id: 10,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
  // {
  //   id: 12,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
  // {
  //   id: 13,
  //   descripcion_equipo:
  //     "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting",
  //   valor_equipo: "$15.458.164",
  //   fecha_compra: "22/05/2020",
  //   tipo_de_equipo: "Portatil",
  //   proyecto_principal: "Proyecto CTeI",
  // },
];

export const talentRows = [
  {
    id: 1,
    nombre_persona: "Santiago Mendoza",
    nivel_academico: "santiago@gmail.com",
    tipo_contrato: "Contratista",
    estado_contrato: "Ejecución",
  },
  {
    id: 2,
    nombre_persona: "Andres Felipe Suarez",
    nivel_academico: "andres@gmail.com",
    tipo_contrato: "Planta",
    estado_contrato: "Sin iniciar",
  },
  {
    id: 3,
    nombre_persona: "Juan Carlos Muñoz",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Temporal",
    estado_contrato: "Terminado",
  },
  {
    id: 4,
    nombre_persona: "Santiago Ventrez",
    nivel_academico: "fdez@gmail.com",
    tipo_contrato: "Provisional",
    estado_contrato: "Suspendido",
  },
  // {
  //   id: 5,
  //   nombre_persona: "Santiago Ventrez",
  //   nivel_academico: "fdez@gmail.com",
  //   tipo_contrato: "Contratista",
  //   estado_contrato: "Concluido",
  // },
  // {
  //   id: 6,
  //   nombre_persona: "Santiago Ventrez",
  //   nivel_academico: "fdez@gmail.com",
  //   tipo_contrato: "Auxiliar",
  //   estado_contrato: "Vigente",
  // },
  // {
  //   id: 7,
  //   nombre_persona: "Santiago Ventrez",
  //   nivel_academico: "fdez@gmail.com",
  //   tipo_contrato: "Contratista",
  //   estado_contrato: "Vigente",
  // },
  // {
  //   id: 8,
  //   nombre_persona: "Santiago Ventrez",
  //   nivel_academico: "fdez@gmail.com",
  //   tipo_contrato: "Contratista",
  //   estado_contrato: "Concluido",
  // },
  // {
  //   id: 9,
  //   nombre_persona: "Santiago Ventrez",
  //   nivel_academico: "fdez@gmail.com",
  //   tipo_contrato: "Contratista",
  //   estado_contrato: "Concluido",
  // },
  // {
  //   id: 10,
  //   nombre_persona: "Santiago Ventrez",
  //   nivel_academico: "fdez@gmail.com",
  //   tipo_contrato: "Contratista",
  //   estado_contrato: "Concluido",
  // },
  // {
  //   id: 12,
  //   nombre_persona: "Santiago Ventrez",
  //   nivel_academico: "fdez@gmail.com",
  //   tipo_contrato: "Contratista",
  //   estado_contrato: "Concluido",
  // },
  // {
  //   id: 13,
  //   nombre_persona: "Santiago Ventrez",
  //   nivel_academico: "fdez@gmail.com",
  //   tipo_contrato: "Contratista",
  //   estado_contrato: "Concluido",
  // },
];

export const productRows = [
  {
    id: 8000,
    nombre_producto: "Articulo Sometido en revista Indexada",
    tipologia_producto: "2.2.1.1 Artículos de investigación A1",
    fecha_registro: "15/08/2020",
    semillero: "SIPI (Semillero de Investigación en Proyectos e Ingeniería)",
    talento_humano: "Santiago Mendoza",
  },
  {
    id: 8040,
    nombre_producto: "Informe de investigación",
    tipologia_producto: "Informe de investigación",
    fecha_registro: "25/05/2019",
    semillero: "SIPI (Semillero de Investigación en Proyectos e Ingeniería)",
    talento_humano: "Juan Carlos Muñoz",
  },
  {
    id: 8009,
    nombre_producto: "Articulo Sometido en revista Indexada",
    tipologia_producto: "REDTIS (Semillero de Investigación en Redes",
    fecha_registro: "12/07/2020",
    semillero: "2.2.1.1 Artículos de investigación A1",
    talento_humano: "Santiago Ventrez",
  },
  // {
  //   id: 65158,
  //   nombre_producto: "Producto alto",
  //   tipologia_producto: "Notas Cientificas",
  //   fecha_registro: "15/08/2020",
  //   semillero: "Diseño",
  //   talento_humano: "Susan",
  // },
  // {
  //   id: 65068,
  //   nombre_producto: "Producto alto",
  //   tipologia_producto: "Productos Emprendimiento",
  //   fecha_registro: "02/02/2020",
  //   semillero: "Investigacion",
  //   talento_humano: "Pepe Fdez",
  // },
  // {
  //   id: 65468,
  //   nombre_producto: "Producto alto",
  //   tipologia_producto: "Productos Emprendimiento",
  //   fecha_registro: "02/02/2020",
  //   semillero: "Investigacion",
  //   talento_humano: "Pepe Fdez",
  // },
  // {
  //   id: 64168,
  //   nombre_producto: "Producto alto",
  //   tipologia_producto: "Productos Emprendimiento",
  //   fecha_registro: "02/02/2020",
  //   semillero: "Investigacion",
  //   talento_humano: "Pepe Fdez",
  // },
  // {
  //   id: 63168,
  //   nombre_producto: "Producto alto",
  //   tipologia_producto: "Productos Emprendimiento",
  //   fecha_registro: "02/02/2020",
  //   semillero: "Investigacion",
  //   talento_humano: "Pepe Fdez",
  // },
  // {
  //   id: 62168,
  //   nombre_producto: "Producto alto",
  //   tipologia_producto: "Productos Emprendimiento",
  //   fecha_registro: "02/02/2020",
  //   semillero: "Investigacion",
  //   talento_humano: "Pepe Fdez",
  // },
];

export const finanzaData = [
  {
    name: "2017",
    Inversion: 4000,
  },
  {
    name: "2018",
    Inversion: 2113,
  },
  {
    name: "2019",
    Inversion: 3653,
  },
  {
    name: "2020",
    Inversion: 5832,
  },
  {
    name: "2021",
    Inversion: 2454,
  },
];

export const talentData = [
  {
    name: "2017",
    Contratados: 25,
  },
  {
    name: "2018",
    Contratados: 10,
  },
  {
    name: "2019",
    Contratados: 14,
  },
  {
    name: "2020",
    Contratados: 45,
  },
  {
    name: "2021",
    Contratados: 10,
  },
];

export const proyectRows = [
  {
    id: 6234,
    nombre_proyecto:
      "Blockchain como solución tecnológica para la gestión de firmas digitales utilizando sistemas de reconocimiento biométrico",
    valor_proyecto: "$52.405.000",
    valor_servicios_personales: "$42.799.245",
    valor_compra_equipos: "$2.600.000",
    valor_software: "$0",
    fecha_cierre_proyecto: "02/12/2020",
    estado_proyecto: "Terminado",
  },
  {
    id: 3432,
    nombre_proyecto:
      "Estrategias didácticas mediante herramientas Lego para el desarrollo de habilidades blandas de los aprendices del  Centro de Servicios y Gestión Empresarial.",
    valor_proyecto: "$47.460.000",
    valor_servicios_personales: "$23.063.363",
    valor_compra_equipos: "$21.309.273",
    valor_software: "$0",
    fecha_cierre_proyecto: "02/11/2019",
    estado_proyecto: "Terminado",
  },
  {
    id: 3412,
    nombre_proyecto:
      "Implementación de un laboratorio para formulación de proyectos, anílisis y procesamiento de datos fortaleciendo la investigación del Centro de Servicios y Gestión Empresarial",
    valor_proyecto: "$50.000.000",
    valor_servicios_personales: "$0",
    valor_compra_equipos: "$22.434.262",
    valor_software: "$22.998.630",
    fecha_cierre_proyecto: "26/02/2019",
    estado_proyecto: "Terminado",
  },
  // {
  //   id: 65158,
  //   nombre_proyecto: "Solución CART",
  //   valor_proyecto: "$12.795.487",
  //   valor_servicios_personales: "$0",
  //   valor_compra_equipos: "$45.789.415",
  //   valor_software: "$0",
  //   fecha_cierre_proyecto: "22/02/2020",
  //   estado_proyecto: "Cerrado",
  // },
  // {
  //   id: 65068,
  //   nombre_proyecto: "Solución CART",
  //   valor_proyecto: "$12.795.487",
  //   valor_servicios_personales: "$0",
  //   valor_compra_equipos: "$45.789.415",
  //   valor_software: "$0",
  //   fecha_cierre_proyecto: "22/02/2020",
  //   estado_proyecto: "Cerrado",
  // },
  // {
  //   id: 65468,
  //   nombre_proyecto: "Solución CART",
  //   valor_proyecto: "$12.795.487",
  //   valor_servicios_personales: "$0",
  //   valor_compra_equipos: "$45.789.415",
  //   valor_software: "$0",
  //   fecha_cierre_proyecto: "22/02/2020",
  //   estado_proyecto: "Cerrado",
  // },
  // {
  //   id: 64168,
  //   nombre_proyecto: "Solución CART",
  //   valor_proyecto: "$12.795.487",
  //   valor_servicios_personales: "$0",
  //   valor_compra_equipos: "$45.789.415",
  //   valor_software: "$0",
  //   fecha_cierre_proyecto: "22/02/2020",
  //   estado_proyecto: "Cerrado",
  // },
  // {
  //   id: 63168,
  //   nombre_proyecto: "Solución CART",
  //   valor_proyecto: "$12.795.487",
  //   valor_servicios_personales: "$0",
  //   valor_compra_equipos: "$45.789.415",
  //   valor_software: "$0",
  //   fecha_cierre_proyecto: "22/02/2020",
  //   estado_proyecto: "Cerrado",
  // },
  // {
  //   id: 62168,
  //   nombre_proyecto: "Solución CART",
  //   valor_proyecto: "$12.795.487",
  //   valor_servicios_personales: "$0",
  //   valor_compra_equipos: "$45.789.415",
  //   valor_software: "$0",
  //   fecha_cierre_proyecto: "22/02/2020",
  //   estado_proyecto: "Cerrado",
  // },
];
